# GitHub Pages Configuration
# This file ensures your website is served correctly

# Include all files for GitHub Pages
include:
  - "_*"
  - ".*"

# Exclude unnecessary files from the build
exclude:
  - "node_modules"
  - ".git"
  - ".gitignore"
  - "*.log"

# Set the source for GitHub Pages (usually not needed but good for clarity)
source: .

# Use Jekyll processing (set to false for pure static sites)
markdown: kramdown
highlighter: rouge

# Site settings for better SEO
title: "Study Notes Repository"
description: "Access and download PDF notes and markdown files"
url: "https://your-username.github.io"
baseurl: "/your-repo-name"

# GitHub Pages specific settings
github:
  repository_name: "your-repo-name"
  owner_name: "your-username"

# Plugins (GitHub Pages automatically includes these)
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Default layout for markdown files
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
